# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/sandbox/vault/wordpress_sites.yml

wordpress_sites:
  sandbox.proteusthemes.com:
    site_hosts:
      - sandbox.proteusthemes.com
    site_install: true
    site_title: ProteusThemes
    admin_user: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].admin_user }}"
    admin_password: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].admin_password }}"
    admin_email: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].admin_email }}"
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_home: http://sandbox.proteusthemes.com
      wp_siteurl: http://sandbox.proteusthemes.com
      db_name: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].env.db_name }}"
      db_user: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].env.db_user }}"
      db_password: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].env.db_password }}"
      db_prefix: "{{ vault_wordpress_sites['sandbox.proteusthemes.com'].env.db_prefix }}"
  xml-io.proteusthemes.com:
    site_hosts:
      - xml-io.proteusthemes.com
    site_install: true
    site_title: ProteusThemes
    admin_user: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].admin_user }}"
    admin_password: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].admin_password }}"
    admin_email: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].admin_email }}"
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
    env:
      wp_home: http://xml-io.proteusthemes.com
      wp_siteurl: http://xml-io.proteusthemes.com
      db_name: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].env.db_name }}"
      db_user: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].env.db_user }}"
      db_password: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].env.db_password }}"
      db_prefix: "{{ vault_wordpress_sites['xml-io.proteusthemes.com'].env.db_prefix }}"
