# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  sandbox.proteusthemes.com:
    site_hosts:
      - sandbox.proteusthemes.com
    site_install: true
    site_title: ProteusThemes
    admin_user: proteusnet
    admin_password: admin
    admin_email: proteusnet@proteusthemes.dev
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://sandbox.proteusthemes.com
      wp_siteurl: http://sandbox.proteusthemes.com
      wp_env: sandbox
      db_name: example_sandbox
      db_user: example_dbuser
      db_password: example_dbpassword
      db_prefix: sb_
  xml-io.proteusthemes.com:
    site_hosts:
      - xml-io.proteusthemes.com
    site_install: true
    site_title: ProteusThemes
    admin_user: proteusnet
    admin_password: admin
    admin_email: proteusnet@proteusthemes.dev
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://xml-io.proteusthemes.com
      wp_siteurl: http://xml-io.proteusthemes.com
      wp_env: sandbox
      db_name: example_sandbox
      db_user: example_dbuser
      db_password: example_dbpassword
      db_prefix: xmlio_
