---
- name: Check if deploy_before scripts exist
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  register: deploy_before_paths
  loop: "{{ deploy_before | default([]) }}"

- include_tasks: "{{ include_path.item }}"
  loop: "{{ deploy_before_paths.results }}"
  loop_control:
    loop_var: include_path
  when: include_path.stat.exists
  tags: deploy-before

- import_tasks: initialize.yml
- import_tasks: update.yml
- import_tasks: prepare.yml
- import_tasks: build.yml
- import_tasks: share.yml
- import_tasks: finalize.yml

- name: Check if deploy_after scripts exist
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  register: deploy_after_paths
  loop: "{{ deploy_after | default([]) }}"

- include_tasks: "{{ include_path.item }}"
  loop: "{{ deploy_after_paths.results }}"
  loop_control:
    loop_var: include_path
  when: include_path.stat.exists
  tags: deploy-after
