---
- name: Ensure gpg2 is installed
  apt:
    name: "{{ gpg2_package }}"
    state: "{{ gpg2_package_state | default(apt_security_package_state) }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Download WP-CLI Phar
  get_url:
    url: "{{ wp_cli_phar_url }}"
    dest: /tmp/wp-cli-{{ wp_cli_version }}.phar

- name: Download WP-CLI Phar Signature
  get_url:
    url: "{{ wp_cli_phar_asc_url }}"
    dest: /tmp/wp-cli-{{ wp_cli_version }}.phar.asc

- name: Copy WP-CLI release team public key
  copy:
    src: "{{ wp_cli_pgp_public_key }}"
    dest: /tmp/wp-cli.pgp.gpg
    mode: '0744'

- name: Verify WP-CLI
  block:
    - name: Check GPG signature
      command: gpg2 --lock-never --no-default-keyring --keyring /tmp/wp-cli.pgp.gpg --verify /tmp/wp-cli-{{ wp_cli_version }}.phar.asc /tmp/wp-cli-{{ wp_cli_version }}.phar
      changed_when: false
  rescue:
    - name: Delete invalid WP-CLI Phar file
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/wp-cli-{{ wp_cli_version }}.phar"
        - "/tmp/wp-cli-{{ wp_cli_version }}.phar.asc"
    - name: Fail verification
      fail:
        msg: "WP-CLI Phar signature could not be verified. Please try again."

- name: Install WP-CLI
  command: rsync -c --chmod=0755 --info=name /tmp/wp-cli-{{ wp_cli_version }}.phar {{ wp_cli_bin_path }}
  args:
    warn: false
  register: wp_cli
  changed_when: wp_cli.stdout == 'wp-cli-' + wp_cli_version + '.phar'

- name: Retrieve WP-CLI tab completions
  command: curl -4Ls {{ wp_cli_completion_url }} -o /tmp/wp-completion-{{ wp_cli_version }}.bash
  args:
    creates: /tmp/wp-completion-{{ wp_cli_version }}.bash
    warn: false

- name: Install WP-CLI tab completions
  command: rsync -c --chmod=0644 --info=name /tmp/wp-completion-{{ wp_cli_version }}.bash {{ wp_cli_completion_path }}
  args:
    warn: false
  register: wp_cli_completion
  changed_when: wp_cli_completion.stdout == 'wp-completion-' + wp_cli_version + '.bash'

- name: Install WP-CLI packages
  command: wp package install {{ item }}
  become: true
  become_user: "{{ web_user }}"
  register: wp_cli_packages_installed
  changed_when:
    - "'Nothing to install or update' not in wp_cli_packages_installed.stdout"
    - "'Package operations: 0 installs, 0 updates, 0 removals' not in wp_cli_packages_installed.stdout"
  with_items: "{{ wp_cli_packages }}"
