---
- name: Install Xdebug
  apt:
    name: "{{ php_xdebug_package }}"
    state: "{{ php_xdebug_package_state | default(apt_dev_package_state) }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Template the Xdebug configuration file
  template:
    src: xdebug.ini.j2
    dest: /etc/php/{{ php_version }}/mods-available/xdebug.ini
    mode: '0644'
  notify: reload php-fpm

- name: Ensure 20-xdebug.ini is present
  file:
    src: /etc/php/{{ php_version }}/mods-available/xdebug.ini
    dest: /etc/php/{{ php_version }}/fpm/conf.d/20-xdebug.ini
    state: link
  notify: reload php-fpm

- name: Disable Xdebug CLI
  file:
    path: /etc/php/{{ php_version }}/cli/conf.d/20-xdebug.ini
    state: absent
