---
- name: Check for composer.json in project root or project_subtree_path
  stat:
    path: "{{ deploy_helper.new_release_path }}/composer.json"
  register: composer_json

- name: Fail if composer.json not found
  fail:
    msg: "Unable to find a `composer.json` file in the root of '{{ deploy_helper.new_release_path }}'. Make sure your repo has a `composer.json` file in its root or edit `repo_subtree_path` for '{{ site }}' in `wordpress_sites.yml` so it points to the directory with a `composer.json` file."
  when: not composer_json.stat.exists

- name: Setup composer authentications
  composer:
    command: config
    arguments: --auth http-basic.{{ composer_authentication.hostname | quote }} {{ composer_authentication.username | quote }} {{ composer_authentication.password | default("") | quote }}
    working_dir: "{{ deploy_helper.new_release_path }}"
  no_log: true
  changed_when: false
  when:
    - composer_authentication.hostname is defined and composer_authentication.hostname != ""
    - composer_authentication.username is defined and composer_authentication.username != ""
  loop: "{{ composer_authentications | default([]) }}"
  loop_control:
    loop_var: composer_authentication
    label: "{{ composer_authentication.hostname }}"

- name: Run composer check
  composer:
    command: check-platform-reqs
    working_dir: "{{ deploy_helper.new_release_path }}"
  when: composer_platform_requirements_check

- name: Install Composer dependencies
  composer:
    no_scripts: "{{ composer_no_scripts }}"
    classmap_authoritative: "{{ composer_classmap_authoritative }}"
    working_dir: "{{ deploy_helper.new_release_path }}"
