---
- block:
  - name: Warn about updating network database.
    debug:
      msg: "Updating the network database could take a long time with a large number of sites."
    when: project.update_db_on_deploy | default(update_db_on_deploy) and project.multisite.enabled | default(false)

  - name: Update WP database
    command: wp core update-db {{ project.multisite.enabled | default(false) | ternary('--network', '') }}
    args:
      chdir: "{{ deploy_helper.current_path }}"
    when: project.update_db_on_deploy | default(update_db_on_deploy)

  - name: Get WP theme template and stylesheet roots
    shell: >
      {% if not project.multisite.enabled | default(false) %}
        wp option get {{ item }} --skip-plugins
      {% else %}
        wp site list --field=url | xargs -I {} bash -c 'export url="{}"; echo -n "$url " && wp option get {{ item }} --skip-plugins --url=$url || echo'
      {% endif %}
    args:
      chdir: "{{ deploy_helper.current_path }}"
    register: wp_template_root
    changed_when: false
    failed_when: wp_template_root.stderr != ""
    when: update_wp_theme_paths | default(true) | bool
    with_items:
      - template_root
      - stylesheet_root

  - name: Update WP theme paths
    command: >
      wp option set {{ item[0].option }}
      {{ item[1] | regex_replace('.*' + deploy_helper.releases_path + '/[0-9]*(.*)', deploy_helper.new_release_path + '\1') }}
      {% if project.multisite.enabled | default(false) %} --url={{ item[1].split(' ')[0] }}{% endif %}
    args:
      chdir: "{{ deploy_helper.current_path }}"
    when: update_wp_theme_paths | default(true) | bool
    with_subelements:
      - "[{% for result in wp_template_root.results %}{'option': '{{ result.item }}', 'stdout_lines': {{ result.stdout_lines | select('search', deploy_helper.releases_path) | list }}},{% endfor %}]"
      - stdout_lines

  when: wp_installed | success

- name: Reload php-fpm
  shell: sudo service php7.1-fpm reload
  args:
    warn: false
