php_extensions_default:
  php7.4-bcmath: "{{ apt_package_state }}"
  php7.4-cli: "{{ apt_package_state }}"
  php7.4-curl: "{{ apt_package_state }}"
  php7.4-dev: "{{ apt_package_state }}"
  php7.4-fpm: "{{ apt_package_state }}"
  php7.4-imagick: "{{ apt_package_state }}"
  php7.4-intl: "{{ apt_package_state }}"
  php7.4-mbstring: "{{ apt_package_state }}"
  php7.4-mysql: "{{ apt_package_state }}"
  php7.4-xml: "{{ apt_package_state }}"
  php7.4-xmlrpc: "{{ apt_package_state }}"
  php7.4-zip: "{{ apt_package_state }}"

php_memcached_packages:
  php7.4-memcached: "{{ apt_package_state }}"

php_xdebug_package: php7.4-xdebug
