---
nginx_ppa: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
nginx_package: nginx
nginx_conf: nginx.conf.j2
nginx_path: /etc/nginx
nginx_worker_connections: 8000
nginx_logs_root: /var/log/nginx
nginx_user: www-data www-data
nginx_fastcgi_buffers: 8 8k
nginx_fastcgi_buffer_size: 8k
nginx_fastcgi_read_timeout: 120s

# Fastcgi cache params
nginx_cache_path: /var/cache/nginx
nginx_cache_key_storage_size: 10m
nginx_cache_size: 250m
nginx_cache_inactive: 1h

# Resolver for ACME and other dynamic operations
nginx_resolver: 1.1.1.1 8.8.8.8
nginx_resolver_timeout: 5s

# ACME (Let's Encrypt) params
acme_server: https://acme-v02.api.letsencrypt.org/directory
acme_account_key_type: ecdsa:256
acme_certificate_key_type: ecdsa:256
acme_ssl_verify: "on"
nginx_acme_state_path: /var/lib/nginx/acme
nginx_acme_zone_size: 1M
