---
- name: Download client cert
  get_url:
    url: "{{ item.value.ssl.client_cert_url }}"
    dest: "{{ nginx_ssl_path }}/client-{{ (item.value.ssl.client_cert_url | hash('md5'))[:7] }}.crt"
    mode: '0640'
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: ssl_enabled and 'client_cert_url' in item.value.ssl
