---
- name: Install {{ mysql_provider }} client and server
  include: "{{ mysql_provider }}.yml"

- block:
  - name: Disable binary logging
    template:
      src: disable-binary-logging.cnf
      dest: /etc/mysql/conf.d
      owner: root
      group: root
    when: binary_logging_disabled

  - name: Restart MySQL Server
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Set root user password
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      state: present
    with_items:
      - "{{ inventory_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Copy .my.cnf file with root password credentials.
    template:
      src: my.cnf.j2
      dest: ~/.my.cnf
      owner: root
      group: root
      mode: 0600

  - name: Delete anonymous MySQL server users
    mysql_user:
      user: ""
      host: "{{ item }}"
      state: absent
    with_items:
      - localhost
      - "{{ inventory_hostname }}"
      - "{{ ansible_hostname }}"

  - name: Remove the test database
    mysql_db:
      name: test
      state: absent

  when: not sites_using_remote_db | count