---
- name: Get real path of current symlinked release
  command: "readlink {{ project_current_path }}"
  args:
    chdir: "{{ project_root }}"
  register: current_release_readlink_result
  changed_when: false

- name: Clean up old and failed releases
  deploy_helper:
    state: clean
    path: "{{ project_root }}"
    current_path: "{{ project_current_path }}"
    release: "{{ current_release_readlink_result.stdout }}"
    keep_releases: "{{ project.deploy_keep_releases | default(deploy_keep_releases | default(omit)) }}"

- import_tasks: user-release.yml
  when: release is defined

- import_tasks: prior-release.yml
  when: release is not defined

- name: Link 'current' directory to target release
  file:
    path: "{{ project_root }}/{{ project_current_path }}"
    src: "{{ new_release_path }}"
    state: link

- name: Write unfinished file to old symlinked release
  file:
    path: "{{ current_release_readlink_result.stdout }}/DEPLOY_UNFINISHED"
    state: touch
    mode: '0644'
