ferm_input_list:
  - type: dport_accept
    dport: [http, https]
    filename: nginx_accept
  - type: dport_limit
    dport: [ssh]
    seconds: 300
    hits: 20

# Documentation: https://roots.io/trellis/docs/security/
# If `sshd_permit_root_login` is `false`, `admin_user` must be:
# (1) in 'users' (`users.yml`) with sudo group, and
# (2) in `sudoer_passwords` (unless `sudoer_passwordless` is true).
sshd_permit_root_login: true
sshd_password_authentication: false
sudoer_passwordless: false
