# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: "{{ vault_admin_user }}"

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      # - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      - https://github.com/primozcigler.keys
  - name: "{{ admin_user }}"
    groups:
      - "{{ web_group }}"
      - sudo
    keys:
      - https://github.com/primozcigler.keys
  - name: primoz
    groups:
      - "{{ web_group }}"
      - sudo
    keys:
      - https://github.com/primozcigler.keys

web_user: "{{ vault_web_user }}"
web_group: "{{ vault_web_group }}"
web_sudoers: "{{ vault_web_sudoers }}"
