# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: "{{ vault_admin_user }}"

# Also define 'vault_sudoer_passwords' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      # - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      - https://github.com/primozcigler.keys
  - name: "{{ admin_user }}"
    groups:
      - "{{ web_group }}"
      - sudo
    keys:
      - https://github.com/primozcigler.keys
  - name: primoz
    groups:
      - "{{ web_group }}"
      - sudo
    keys:
      - https://github.com/primozcigler.keys
  - name: marko
    groups:
      - "{{ web_group }}"
    keys:
      - https://github.com/Prelc.keys
  - name: gregor
    groups:
      - "{{ web_group }}"
      - sudo
    keys:
      - https://github.com/capuderg.keys

web_user: "{{ vault_web_user }}"
web_group: "{{ vault_web_group }}"
web_sudoers:
  - "/usr/sbin/service php7.0-fpm *"
