---
- name: Add HHVM apt-key
  apt_key: url="http://dl.hhvm.com/conf/hhvm.gpg.key" state=present

- name: Add HHVM deb
  apt_repository: repo="deb http://dl.hhvm.com/ubuntu {{ ansible_distribution_release }} main"
                  state=present

- name: Install HHVM
  apt: pkg=hhvm state=latest force=yes update_cache=yes

- name: Get HHVM path
  shell: which hhvm
  register: current_hhvm
  ignore_errors: True

- name: Symlink HHVM as php
  file: src="{{ current_hhvm.stdout }}" dest=/usr/bin/php state=link force=yes

- name: HHVM php.ini
  template: src=php.ini.j2 dest=/etc/hhvm/php.ini

- name: HHVM server.ini
  template: src=server.ini.j2 dest=/etc/hhvm/server.ini

- name: Start HHVM service
  service: name=hhvm state=started enabled=true

- name: HHVM server.ini
  template: src=server.ini.j2 dest=/etc/hhvm/server.ini
  notify: restart hhvm
