# Documentation: https://docs.google.com/a/proteusnet.com/document/d/1B6GEpHSMAsxnn4hfh_t-1NvKqh7vHWKNyun3TOaKWM0/edit?usp=sharing
src_domain: "demo.proteusthemes.com" # inside {{ www_root }}
export_domain: "xml-io.proteusthemes.com"
src_url: "https://{{ src_domain }}"
dummy_pass: "{{ vault_dummy_pass }}"

sb_wp_sites:
  sandbox.proteusthemes.com:
    env: # this must match the groups_vars/sandbox
      db_name: "{{ vault_sb_wp_sites['sandbox.proteusthemes.com'].env.db_name }}"
      db_user: "{{ vault_sb_wp_sites['sandbox.proteusthemes.com'].env.db_user }}"
      db_password: "{{ vault_sb_wp_sites['sandbox.proteusthemes.com'].env.db_password }}"
      db_prefix: "{{ vault_sb_wp_sites['sandbox.proteusthemes.com'].env.db_prefix }}"
  xml-io.proteusthemes.com:
    env:
      db_name: "{{ vault_sb_wp_sites['xml-io.proteusthemes.com'].env.db_name }}"
      db_user: "{{ vault_sb_wp_sites['xml-io.proteusthemes.com'].env.db_user }}"
      db_password: "{{ vault_sb_wp_sites['xml-io.proteusthemes.com'].env.db_password }}"
      db_prefix: "{{ vault_sb_wp_sites['xml-io.proteusthemes.com'].env.db_prefix }}"

wp_rsync_opts:
  root:
    - "--delete"
    - "--exclude='.git/'"
    - "--exclude='wp-config.php'"
    - "--exclude='wp-cli.yml'"
    - "--exclude='/google*.html'"
    - "--exclude='/.htaccess'"
    - "--exclude='/wc-logs/'"
    - "--exclude='/wp-content/advanced-cache.php'"
    - "--exclude='/wp-content/uploads/'"
    - "--exclude='/wp-content/cache/'"
    - "--exclude='/wp-content/plugins/wp-rocket/'"
    - "--exclude='/wp-content/plugins/js-style-swicher-*/'"
    - "--exclude='/wp-content/plugins/*-style-switcher/'"
    - "--exclude='/wp-content/mu-plugins/wp-password-bcrypt.php'"
  uploads:
    - "--delete"
    - "--ignore-existing"
    - "--exclude='.*'"
    - "--exclude='Makefile'"

# replace these emails to info@example.com when importing
wp_emails:
  from:
    - 'primoz@proteusnet\.com'
    - 'info@proteusthemes\.com'
    - 'gregor\.capuder@proteusnet\.com'
    - 'jejcic\.jaka@gmail\.com'
    - 'jaka@spaka\.si'
    - 'lena\.gregorcic@proteusnet\.com'
    - 'marko\.prelec@proteusnet\.com'
  to: 'info@example.com'

sites_to_export:
  - hairpress
  - webmarket
  - carpress
  - organique
  - readable
  - buildpress
  - mentalpress
  - cargopress
  - legalpress
  - repairpress
  - structurepress
  - beauty
  - auto
  - hammer
  - bolts

xml_paths:
  local:  "/tmp/xml-exports"
  remote: "{{ www_root }}/artifacts.proteusthemes.com/xml-exports"
