mariadb_version: 10.11
mariadb_ppa: "deb https://mirror.rackspace.com/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main"

mariadb_client_package: mariadb-client
mariadb_server_package: mariadb-server

mysql_binary_logging_disabled: true
mysql_root_user: root

sites_using_remote_db: "[{% for name, site in wordpress_sites.items() | list if site.env is defined and site.env.db_host | default('localhost') != 'localhost' %}'{{ name }}',{% endfor %}]"

mariadb_set_innodb_buffer_pool_size: false
mariadb_innodb_buffer_pool_size: 128M
mariadb_set_innodb_log_file_size: false
mariadb_innodb_log_file_size: 96M
