mariadb_keyserver: "hkp://keyserver.ubuntu.com:80"
mariadb_keyserver_id: "0xF1656F24C74CD1D8"
mariadb_ppa: "deb https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu {{ ansible_distribution_release }} main"

mariadb_client_package: mariadb-client
mariadb_server_package: mariadb-server

mysql_binary_logging_disabled: true
mysql_root_user: root

sites_using_remote_db: "[{% for name, site in wordpress_sites.items() | list if site.env is defined and site.env.db_host | default('localhost') != 'localhost' %}'{{ name }}',{% endfor %}]"
