---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Node.js installation for Linux
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - trusty
      - xenial
  galaxy_tags:
    - development
    - web
