static_sites:
  apps.proteusthemes.com:
    site_hosts:
      - apps.proteusthemes.test
    local_path: ../www/apps.proteusthemes.com
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env: development
