# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: devpw
vault_redis_password: devpw

# Variables to accompany `group_vars/development/sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_sites:
  example.com:
    admin_password: admin
    env:
      db_password: example_dbpassword
