# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: devpw

# Variables to accompany `group_vars/development/apps.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_apps:

  wordpress.com:
    admin_password: admin
    env:
      db_password: example_dbpassword

  laravel.com:
    env:
      db_password: example_dbpassword

