# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  example.com:
    site_hosts:
      - example.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: Example Site
    admin_user: admin
    # admin_password: (defined in group_vars/development/vault.yml)
    admin_email: admin@example.dev
    permalink_structure: "/%postname%/"
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://example.dev
      wp_siteurl: http://example.dev/wp
      wp_env: development
      db_name: example_dev
      db_user: example_dbuser
      # db_password: (defined in group_vars/development/vault.yml)
