# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites

wordpress_sites:
  demo.proteusthemes.com:
    site_hosts:
      - demo.proteusthemes.dev
    local_path: ../www/demo.proteusthemes.com # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: ProteusThemes
    admin_user: proteusnet
    admin_password: admin
    admin_email: proteusnet@proteusthemes.dev
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      wp_home: "http://demo.proteusthemes.dev"
      wp_siteurl: "http://demo.proteusthemes.dev"
      db_name: demo_network
      db_user: proteusnet
      db_password: devpw
      db_prefix: wpsites_
  www.proteusthemes.com:
    site_hosts:
      - www.proteusthemes.dev
    local_path: ../www/www.proteusthemes.com
    site_install: true
    site_title: ProteusThemes
    admin_user: proteusnet
    admin_password: admin
    admin_email: admin@proteusthemes.dev
    multisite:
      enabled: false
      # subdomains: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      wp_home: "http://www.proteusthemes.dev"
      wp_siteurl: "http://www.proteusthemes.dev"
      db_name: pt_core
      db_user: proteusnet
      db_password: devpw
      db_prefix: ptcore_
