---
- name: Add Composer PPA
  apt_repository: repo="ppa:duggan/composer" update_cache=yes

- name: Install Composer
  apt: name=php5-composer state=present force=yes

- name: Composer self update
  shell: composer self-update
