---
- name: disable temporary challenge sites
  import_tasks: disable_challenge_sites.yml

- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: reload php-fpm
  service:
    name: php7.2-fpm
    state: reloaded

- import_tasks: reload_nginx.yml
