static_sites:
  apps.proteusthemes.com:
    site_hosts:
      - apps.proteusthemes.com
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
      duration: 30s
    env: production
  artifacts.proteusthemes.com:
    site_hosts:
      - artifacts.proteusthemes.com
    ssl:
      enabled: false
    cache:
      enabled: false
    php: false
    env: production
  html-demo.proteusthemes.com:
    site_hosts:
      - html-demo.proteusthemes.com
    ssl:
      enabled: false
    cache:
      enabled: false
    env: production
  www.proteusnet.com:
    site_hosts:
      - www.proteusnet.com
    ssl:
      enabled: false
    cache:
      enabled: false
    env: production
