# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  demo.proteusthemes.com:
    site_hosts:
      - demo.proteusthemes.com
    site_title: ProteusThemes Demos
    admin_user: "{{ vault_wordpress_sites['demo.proteusthemes.com'].admin_user }}"
    admin_password: "{{ vault_wordpress_sites['demo.proteusthemes.com'].admin_password }}"
    admin_email: "{{ vault_wordpress_sites['demo.proteusthemes.com'].admin_email }}"
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
    env:
      wp_home: "https://demo.proteusthemes.com"
      wp_siteurl: "https://demo.proteusthemes.com"
      db_user: "{{ vault_wordpress_sites['demo.proteusthemes.com'].env.db_user }}"
      db_password: "{{ vault_wordpress_sites['demo.proteusthemes.com'].env.db_password }}"
      db_prefix: "{{ vault_wordpress_sites['demo.proteusthemes.com'].env.db_prefix }}"
  www.proteusthemes.com:
    site_hosts:
      - www.proteusthemes.com
    site_title: ProteusThemes
    admin_user: "{{ vault_wordpress_sites['www.proteusthemes.com'].admin_user }}"
    admin_password: "{{ vault_wordpress_sites['www.proteusthemes.com'].admin_password }}"
    admin_email: "{{ vault_wordpress_sites['www.proteusthemes.com'].admin_email }}"
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
    env:
      wp_home: "https://www.proteusthemes.com"
      wp_siteurl: "https://www.proteusthemes.com"
      db_user: "{{ vault_wordpress_sites['www.proteusthemes.com'].env.db_user }}"
      db_password: "{{ vault_wordpress_sites['www.proteusthemes.com'].env.db_password }}"
      db_prefix: "{{ vault_wordpress_sites['www.proteusthemes.com'].env.db_prefix }}"
