---
- include: self-signed-certificate.yml
  tags: statis-sites-setup-self-signed-certificate

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ static_sites }}"

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/logs/{{ item.key }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ static_sites }}"

- name: Create web root of sites
  file:
    path: "{{ www_root }}/{{ item.key }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0775
    state: directory
  with_dict: "{{ static_sites }}"

- include: nginx.yml
  tags: static-sites-setup-nginx
