---
- name: Create web root of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/{{ item.value.public_path | default('web') }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become_method: sudo

- name: Create shared folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/shared"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become_method: sudo

- name: Change site owner to user
  file:
    path: "{{ www_root }}/{{ item.key }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    state: directory
    recurse: yes
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become_method: sudo
  when: chown_site_directory | default(false)
