---
- name: Add PHP 7.0 PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes

- name: Install PHP 7.0
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-mcrypt
  - php7.0-mysql
  - php7.0-opcache
  - php7.0-xml
  - php7.0-xmlrpc
  - php7.0-zip

- name: Install Xdebug
  apt:
    name: php-xdebug
    state: latest
  when: xdebug_install | default(false)

- name: xdebug configuration file
  template:
    src: xdebug.ini.j2
    dest: /etc/php/7.0/mods-available/xdebug.ini
  when: xdebug_install | default(false)

- name: Start php7.0-fpm service
  service:
    name: php7.0-fpm
    state: started
    enabled: true

- name: Create socket directory
  file:
    path: /var/run/php7.0-fpm/
    state: directory

- name: Disable default pool
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.0/fpm/pool.d/www.disabled
  when: disable_default_pool
  notify: reload php-fpm

- name: PHP configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/fpm/php.ini
  notify: reload php-fpm

- name: php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/wordpress.conf
  notify: reload php-fpm
