---
- name: Add PHP PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes

- name: Install PHP and extensions
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_dict: "{{ php_extensions }}"

- name: Start php fpm service
  service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: true

- name: Find existing php fpm services
  find:
    paths: /etc/init.d
    patterns: "^php((?!{{ php_version }})(\\d\\.\\d))-fpm$"
    use_regex: true
  register: old_php_fpm_services

- name: Stop old php-fpm services
  service:
    name: "{{ item.path | basename }}"
    state: stopped
    enabled: false
  loop: "{{ old_php_fpm_services.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  notify: reload php-fpm

- name: Copy PHP-FPM configuration file
  template:
    src: php-fpm.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    mode: '0644'
  notify: reload php-fpm

- name: Copy PHP CLI configuration file
  template:
    src: php-cli.ini.j2
    dest: /etc/php/{{ php_version }}/cli/php.ini
    mode: '0644'
